// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Royal.Data;

namespace Royal.Data.Migrations
{
    [DbContext(typeof(RoyalContext))]
    [Migration("20201004103625_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Royal.Domain.Knight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoyalFamilyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoyalFamilyId");

                    b.ToTable("Knights");
                });

            modelBuilder.Entity("Royal.Domain.KnightVows", b =>
                {
                    b.Property<int>("KnightId")
                        .HasColumnType("int");

                    b.Property<int>("VowId")
                        .HasColumnType("int");

                    b.HasKey("KnightId", "VowId");

                    b.HasIndex("VowId");

                    b.ToTable("Vows");
                });

            modelBuilder.Entity("Royal.Domain.RoyalFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Royal.Domain.Vow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vow");
                });

            modelBuilder.Entity("Royal.Domain.Knight", b =>
                {
                    b.HasOne("Royal.Domain.RoyalFamily", "RoyalFamily")
                        .WithMany()
                        .HasForeignKey("RoyalFamilyId");
                });

            modelBuilder.Entity("Royal.Domain.KnightVows", b =>
                {
                    b.HasOne("Royal.Domain.Knight", "Knight")
                        .WithMany("Vows")
                        .HasForeignKey("KnightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Royal.Domain.Vow", "Vow")
                        .WithMany("KnightVows")
                        .HasForeignKey("VowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
